/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

import Controller.ControladorCliente;
import Model.Cliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo
 */
public class Ejecutor extends javax.swing.JFrame {
    DefaultTableModel modelo;
    
    public Ejecutor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("MOV-UPTL");
        modelo = (DefaultTableModel) this.jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        data_cedula = new javax.swing.JTextField();
        data_nombres = new javax.swing.JTextField();
        data_ciudad = new javax.swing.JTextField();
        data_direccion = new javax.swing.JTextField();
        data_correo = new javax.swing.JTextField();
        data_marca = new javax.swing.JTextField();
        data_modelo = new javax.swing.JTextField();
        data_numero = new javax.swing.JTextField();
        jButton4_facturar = new javax.swing.JButton();
        jButton1_registrar = new javax.swing.JButton();
        jButton2_modificar = new javax.swing.JButton();
        jButton3_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5_actualizarTabla = new javax.swing.JButton();
        fondo_ejecutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_Titulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_Titulo.setText("SISTEMA DE GESTION Y FACTURACION");
        jLabel1_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS TELEFONO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("*Cedula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("*Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Ciudad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("*Direcccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Marca:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Modelo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("*Numero:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        data_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_cedulaActionPerformed(evt);
            }
        });
        getContentPane().add(data_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        data_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_nombresActionPerformed(evt);
            }
        });
        getContentPane().add(data_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, -1));
        getContentPane().add(data_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, -1));
        getContentPane().add(data_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, -1));
        getContentPane().add(data_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 130, -1));
        getContentPane().add(data_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 140, -1));
        getContentPane().add(data_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 140, -1));
        getContentPane().add(data_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 140, -1));

        jButton4_facturar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4_facturar.setText("FACTURAR");
        jButton4_facturar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4_facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_facturarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4_facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 150, 60));

        jButton1_registrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1_registrar.setText("REGISTRAR");
        jButton1_registrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 150, 60));

        jButton2_modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2_modificar.setText("MODIFICAR");
        jButton2_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 150, 60));

        jButton3_eliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3_eliminar.setText("ELIMINAR");
        jButton3_eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 150, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Correo", "Direccion", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Cedula");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Correo");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Direccion");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Ciudad");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 600, 200));

        jButton5_actualizarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar-flecha.png"))); // NOI18N
        jButton5_actualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_actualizarTablaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5_actualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 70, 50));

        fondo_ejecutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        fondo_ejecutor.setText("jLabel11");
        getContentPane().add(fondo_ejecutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_cedulaActionPerformed

    private void data_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_nombresActionPerformed

    private void jButton1_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_registrarActionPerformed
        // Logica para REGISTRAR CLIENTE
        ControladorCliente ctrlCliente = new ControladorCliente();

        if (!data_cedula.getText().isEmpty() && !data_nombres.getText().isEmpty() && !data_direccion.getText().isEmpty() && !data_numero.getText().isEmpty()) {
            Cliente cliente = new Cliente();
            cliente.setCedula(data_cedula.getText().trim());
            cliente.setNombres(data_nombres.getText().trim());
            cliente.setCiudad(data_ciudad.getText().trim());
            cliente.setDireccion(data_direccion.getText().trim());
            cliente.setMarca(data_marca.getText().trim());
            cliente.setModelo(data_modelo.getText().trim());
            cliente.setNumero(data_numero.getText().trim());
            cliente.setCorreo(data_correo.getText().trim());

            if (!ctrlCliente.existeCliente(data_cedula.getText().trim())) {
                ctrlCliente.resgistrarCliente(cliente);
                JOptionPane.showMessageDialog(null,"Registro Completo");
                this.limpiarCampos();
            } else {
                limpiarCampos();
                JOptionPane.showMessageDialog(null,"Cliente Existente en Base de Datos");
            }
        } else {
            JOptionPane.showMessageDialog(null,"Completar los campos obligatorios");
        }
        
    }//GEN-LAST:event_jButton1_registrarActionPerformed

    private void jButton2_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_modificarActionPerformed
        // Logica MODIFICAR CLIENTE
        ControladorCliente controladorCliente_3 = new ControladorCliente();
        
        if (!data_cedula.getText().isEmpty()) {
            Cliente cliente = new Cliente();
            cliente.setCedula(data_cedula.getText().trim());
            cliente.setNombres(data_nombres.getText().trim());
            cliente.setCiudad(data_ciudad.getText().trim());
            cliente.setDireccion(data_direccion.getText().trim());
            cliente.setMarca(data_marca.getText().trim());
            cliente.setModelo(data_modelo.getText().trim());
            cliente.setNumero(data_numero.getText().trim());
            cliente.setCorreo(data_correo.getText().trim());

            controladorCliente_3.modificarCliente(cliente);
            limpiarCampos();
            JOptionPane.showMessageDialog(null,"Exitoso");

        } else {
            JOptionPane.showMessageDialog(null,"Completar campo cedula");
        }

    }//GEN-LAST:event_jButton2_modificarActionPerformed

    private void jButton5_actualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_actualizarTablaActionPerformed
        ControladorCliente controladorCliente_2 = new ControladorCliente();
        controladorCliente_2.mostrarCliente();
        
        while(modelo.getRowCount() > 0)
            this.modelo.removeRow(0);

        for (Cliente cliente : controladorCliente_2.getListaClientes()) 
            this.modelo.addRow(new Object[]{cliente.getCedula(),cliente.getNombres(),cliente.getCorreo(),cliente.getDireccion(),cliente.getCiudad()});
        }
//GEN-LAST:event_jButton5_actualizarTablaActionPerformed

    private void jButton3_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_eliminarActionPerformed
        // Logica ELIMINAR CLIENTE
        ControladorCliente controladorCliente = new ControladorCliente();
        
        if (!data_cedula.getText().isEmpty()) {

            controladorCliente.eliminarCliente(data_cedula.getText().trim());
            limpiarCampos();
            JOptionPane.showMessageDialog(null,"Exitoso");

        } else {
            JOptionPane.showMessageDialog(null,"Completar campo cedula");
        }
        
    }//GEN-LAST:event_jButton3_eliminarActionPerformed

    private void jButton4_facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_facturarActionPerformed
        // LOGICA FACTURA
           Factura ventana2 = new Factura();
           ventana2.setVisible(true);
    }//GEN-LAST:event_jButton4_facturarActionPerformed

    private void limpiarCampos() {
        data_cedula.setText("");
        data_ciudad.setText("");
        data_correo.setText("");
        data_direccion.setText("");
        data_marca.setText("");
        data_modelo.setText("");
        data_nombres.setText("");
        data_numero.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data_cedula;
    private javax.swing.JTextField data_ciudad;
    private javax.swing.JTextField data_correo;
    private javax.swing.JTextField data_direccion;
    private javax.swing.JTextField data_marca;
    private javax.swing.JTextField data_modelo;
    private javax.swing.JTextField data_nombres;
    private javax.swing.JTextField data_numero;
    private javax.swing.JLabel fondo_ejecutor;
    private javax.swing.JButton jButton1_registrar;
    private javax.swing.JButton jButton2_modificar;
    private javax.swing.JButton jButton3_eliminar;
    private javax.swing.JButton jButton4_facturar;
    private javax.swing.JButton jButton5_actualizarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1_Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
