/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Controller.ControladorPlanes;

/**
 *
 * @author Pablo
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        data_PlanMovil = new javax.swing.JComboBox<>();
        data_cedula = new javax.swing.JTextField();
        data_minutos = new javax.swing.JTextField();
        data_megas = new javax.swing.JTextField();
        data_MinutosInternacional = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        data_tarifaBase = new javax.swing.JTextField();
        data_descuento = new javax.swing.JTextField();
        data_CostoMinutosInternacional = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        data_costoMinuto1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        data_costoMegas1 = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_Titulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_Titulo.setText("FACTURACION");
        jLabel1_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Plan Movil:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Minutos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Megas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Minutos Internacionales");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("FACTURAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 150, 60));

        data_PlanMovil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoga una opcion", "PlanPostPagoMinutosMegasEconomico", "PlanPostPagoMinutos", "PlanPostPagoMegas", "PlanPostPagoMinutosMegas" }));
        data_PlanMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_PlanMovilActionPerformed(evt);
            }
        });
        getContentPane().add(data_PlanMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, -1));

        data_cedula.setToolTipText("");
        data_cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(data_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, -1));

        data_minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_minutosActionPerformed(evt);
            }
        });
        getContentPane().add(data_minutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 130, -1));
        getContentPane().add(data_megas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, -1));
        getContentPane().add(data_MinutosInternacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tarifa Base");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Descuento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Costo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));
        getContentPane().add(data_tarifaBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, -1));
        getContentPane().add(data_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 70, -1));

        data_CostoMinutosInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_CostoMinutosInternacionalActionPerformed(evt);
            }
        });
        getContentPane().add(data_CostoMinutosInternacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 70, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Costo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));
        getContentPane().add(data_costoMinuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 70, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Costo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        getContentPane().add(data_costoMegas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 70, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        fondo.setText("jLabel9");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Logica FACTURAR
        ControladorPlanes ctrlPlanes = new ControladorPlanes();

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMinutosMegasEconomico")) {
            
            ctrlPlanes.registrarPlan_PlanPostPagoMinutosMegasEconomico(Double.parseDouble(data_minutos.getText().trim()),
                                                                        Double.parseDouble(data_costoMinuto1.getText().trim()),
                                                                        Double.parseDouble(data_megas.getText().trim()),
                                                                        Double.parseDouble(data_costoMegas1.getText().trim()),
                                                                        Double.parseDouble(data_descuento.getText().trim()),
                                                                        "PlanPostPagoMinutosMegasEconomico",
                                                                        data_cedula.getText().trim());
        }

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMinutos")) {

            ctrlPlanes.registrarPlan_PlanPostPagoMinutos(Double.parseDouble(data_minutos.getText().trim()),
                                                         Double.parseDouble(data_costoMinuto1.getText().trim()),
                                                         Double.parseDouble(data_MinutosInternacional.getText().trim()),
                                                         Double.parseDouble(data_CostoMinutosInternacional.getText().trim()),
                                                         "PlanPostPagoMinutosMegasEconomico",
                                                         data_cedula.getText().trim());
        }

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMegas")) {
            
            ctrlPlanes.registrarPlan_PlanPostPagoMegas(Double.parseDouble(data_megas.getText().trim()),
                                                       Double.parseDouble(data_costoMegas1.getText().trim()),
                                                       Double.parseDouble(data_tarifaBase.getText().trim()),
                                                       "PlanPostPagoMinutosMegasEconomico",
                                                       data_cedula.getText().trim());
        }

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMinutosMegas")) {
            
            ctrlPlanes.registrarPlan_PlanPostPagoMinutosMegas(Double.parseDouble(data_minutos.getText().trim()),
                                                              Double.parseDouble(data_costoMinuto1.getText().trim()),
                                                              Double.parseDouble(data_megas.getText().trim()),
                                                              Double.parseDouble(data_costoMegas1.getText().trim()),
                                                              "PlanPostPagoMinutosMegasEconomico",
                                                              data_cedula.getText().trim());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void data_PlanMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_PlanMovilActionPerformed
        // Logica SELECCION DE PLAN
        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMinutosMegasEconomico")) {
            data_minutos.setBackground(Color.GREEN);
            data_costoMinuto1.setBackground(Color.GREEN);
            data_megas.setBackground(Color.GREEN);
            data_costoMegas1.setBackground(Color.GREEN);
            data_descuento.setBackground(Color.GREEN);
        }

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMinutos")) {
            data_minutos.setBackground(Color.GREEN);
            data_costoMinuto1.setBackground(Color.GREEN);
            data_MinutosInternacional.setBackground(Color.GREEN);
            data_CostoMinutosInternacional.setBackground(Color.GREEN);
        }

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMegas")) {
            data_megas.setBackground(Color.GREEN);
            data_costoMegas1.setBackground(Color.GREEN);
            data_tarifaBase.setBackground(Color.GREEN);
        }

        if (data_PlanMovil.getSelectedItem().equals("PlanPostPagoMinutosMegas")) {
            data_minutos.setBackground(Color.GREEN);
            data_costoMinuto1.setBackground(Color.GREEN);
            data_megas.setBackground(Color.GREEN);
            data_costoMegas1.setBackground(Color.GREEN);
        }
        
    }//GEN-LAST:event_data_PlanMovilActionPerformed

    private void data_minutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_minutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_minutosActionPerformed

    private void data_CostoMinutosInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_CostoMinutosInternacionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_CostoMinutosInternacionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data_CostoMinutosInternacional;
    private javax.swing.JTextField data_MinutosInternacional;
    private javax.swing.JComboBox<String> data_PlanMovil;
    private javax.swing.JTextField data_cedula;
    private javax.swing.JTextField data_costoMegas1;
    private javax.swing.JTextField data_costoMinuto1;
    private javax.swing.JTextField data_descuento;
    private javax.swing.JTextField data_megas;
    private javax.swing.JTextField data_minutos;
    private javax.swing.JTextField data_tarifaBase;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1_Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
